[
  {
    createResult: {
      validationErrors: "column registration_requests.network does not exist",
      error: "Failed to check for duplicate agents",
      success: false,
      state: {
        currentStage: "profile",
        completedPercentage: 60,
        createdResources: [
          "account:0.0.7124916",
          "inbound:0.0.7124918",
          "outbound:0.0.7124917",
          "profile:0.0.7124923",
        ],
        agentMetadata: {
          creator: "MEDICHECK",
          type: "autonomous",
          properties: {
            orgId: "cmh5ixd710007y4fnji28rq2v",
            role: "MANUFACTURER",
            contactEmail: "sojapril00llk@gmail.com",
            contactPhone: "07042932301",
            country: "Nigeria",
          },
        },
        outboundTopicId: "0.0.7124917",
        inboundTopicId: "0.0.7124918",
        pfpTopicId: "",
        profileTopicId: "0.0.7124923",
      },
    },
  },
];
